# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: runtime.proto for package 'runtime'
# Original file comments:
# Copyright 2015 gRPC authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'runtime_pb'

module Runtime
  module RuntimeService
    # ref: https://gitlab.cncf.ci/kubernetes/kubernetes/blob/b6005337947a8de06518076a216af1a82e19e4fe/pkg/kubelet/api/v1alpha1/runtime/api.proto 
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'runtime.RuntimeService'

      # Version returns the runtime name, runtime version, and runtime API version.
      rpc :Version, VersionRequest, VersionResponse
      # RunPodSandbox creates and starts a pod-level sandbox. Runtimes must ensure
      # the sandbox is in the ready state on success.
      rpc :RunPodSandbox, RunPodSandboxRequest, RunPodSandboxResponse
      # CreateContainer creates a new container in specified PodSandbox
      rpc :CreateContainer, CreateContainerRequest, CreateContainerResponse
    end

    Stub = Service.rpc_stub_class
  end
end
