# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: runtime.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "runtime.VersionRequest" do
    optional :version, :string, 1
  end
  add_message "runtime.VersionResponse" do
    optional :version, :string, 1
    optional :runtime_name, :string, 2
    optional :runtime_version, :string, 3
    optional :runtime_api_version, :string, 4
  end
  add_message "runtime.RunPodSandboxRequest" do
    optional :config, :message, 1, "runtime.PodSandboxConfig"
  end
  add_message "runtime.RunPodSandboxResponse" do
    optional :pod_sandbox_id, :string, 1
  end
  add_message "runtime.CreateContainerRequest" do
    optional :pod_sandbox_id, :string, 1
    optional :config, :message, 2, "runtime.ContainerConfig"
    optional :sandbox_config, :message, 3, "runtime.PodSandboxConfig"
  end
  add_message "runtime.CreateContainerResponse" do
    optional :container_id, :string, 1
  end
  add_message "runtime.PodSandboxConfig" do
    optional :metadata, :message, 1, "runtime.PodSandboxMetadata"
    optional :hostname, :string, 2
    optional :log_directory, :string, 3
    optional :dns_config, :message, 4, "runtime.DNSConfig"
    repeated :port_mappings, :message, 5, "runtime.PortMapping"
    map :labels, :string, :string, 6
    map :annotations, :string, :string, 7
    optional :linux, :message, 8, "runtime.LinuxPodSandboxConfig"
  end
  add_message "runtime.PodSandboxMetadata" do
    optional :name, :string, 1
    optional :uid, :string, 2
    optional :namespace, :string, 3
    optional :attempt, :uint32, 4
  end
  add_message "runtime.DNSConfig" do
    repeated :servers, :string, 1
    repeated :searches, :string, 2
    repeated :options, :string, 3
  end
  add_message "runtime.PortMapping" do
    optional :protocol, :enum, 1, "runtime.Protocol"
    optional :container_port, :int32, 2
    optional :host_port, :int32, 3
    optional :host_ip, :string, 4
  end
  add_message "runtime.LinuxPodSandboxConfig" do
    optional :cgroup_parent, :string, 1
    optional :security_context, :message, 2, "runtime.LinuxSandboxSecurityContext"
    map :sysctls, :string, :string, 3
  end
  add_message "runtime.LinuxSandboxSecurityContext" do
    optional :namespace_options, :message, 1, "runtime.NamespaceOption"
    optional :selinux_options, :message, 2, "runtime.SELinuxOption"
    optional :run_as_user, :message, 3, "runtime.Int64Value"
    optional :readonly_rootfs, :bool, 4
    repeated :supplemental_groups, :int64, 5
    optional :privileged, :bool, 6
    optional :seccomp_profile_path, :string, 7
  end
  add_message "runtime.NamespaceOption" do
    optional :host_network, :bool, 1
    optional :host_pid, :bool, 2
    optional :host_ipc, :bool, 3
  end
  add_message "runtime.SELinuxOption" do
    optional :user, :string, 1
    optional :role, :string, 2
    optional :type, :string, 3
    optional :level, :string, 4
  end
  add_message "runtime.ContainerConfig" do
    optional :metadata, :message, 1, "runtime.ContainerMetadata"
    optional :image, :message, 2, "runtime.ImageSpec"
    repeated :command, :string, 3
    repeated :args, :string, 4
    optional :working_dir, :string, 5
    repeated :envs, :message, 6, "runtime.KeyValue"
    repeated :mounts, :message, 7, "runtime.Mount"
    repeated :devices, :message, 8, "runtime.Device"
    map :labels, :string, :string, 9
    map :annotations, :string, :string, 10
    optional :log_path, :string, 11
    optional :stdin, :bool, 12
    optional :stdin_once, :bool, 13
    optional :tty, :bool, 14
    optional :linux, :message, 15, "runtime.LinuxContainerConfig"
  end
  add_message "runtime.ContainerMetadata" do
    optional :name, :string, 1
    optional :attempt, :uint32, 2
  end
  add_message "runtime.ImageSpec" do
    optional :image, :string, 1
  end
  add_message "runtime.KeyValue" do
    optional :key, :string, 1
    optional :value, :string, 2
  end
  add_message "runtime.Mount" do
    optional :container_path, :string, 1
    optional :host_path, :string, 2
    optional :readonly, :bool, 3
    optional :selinux_relabel, :bool, 4
    optional :propagation, :enum, 5, "runtime.MountPropagation"
  end
  add_message "runtime.Device" do
    optional :container_path, :string, 1
    optional :host_path, :string, 2
    optional :permissions, :string, 3
  end
  add_message "runtime.Int64Value" do
    optional :value, :int64, 1
  end
  add_message "runtime.UInt64Value" do
    optional :value, :uint64, 1
  end
  add_message "runtime.LinuxContainerConfig" do
    optional :resources, :message, 1, "runtime.LinuxContainerResources"
    optional :security_context, :message, 2, "runtime.LinuxContainerSecurityContext"
  end
  add_message "runtime.LinuxContainerResources" do
    optional :cpu_period, :int64, 1
    optional :cpu_quota, :int64, 2
    optional :cpu_shares, :int64, 3
    optional :memory_limit_in_bytes, :int64, 4
    optional :oom_score_adj, :int64, 5
    optional :cpuset_cpus, :string, 6
    optional :cpuset_mems, :string, 7
  end
  add_message "runtime.LinuxContainerSecurityContext" do
    optional :capabilities, :message, 1, "runtime.Capability"
    optional :privileged, :bool, 2
    optional :namespace_options, :message, 3, "runtime.NamespaceOption"
    optional :selinux_options, :message, 4, "runtime.SELinuxOption"
    optional :run_as_user, :message, 5, "runtime.Int64Value"
    optional :run_as_username, :string, 6
    optional :readonly_rootfs, :bool, 7
    repeated :supplemental_groups, :int64, 8
    optional :apparmor_profile, :string, 9
    optional :seccomp_profile_path, :string, 10
    optional :no_new_privs, :bool, 11
  end
  add_message "runtime.Capability" do
    repeated :add_capabilities, :string, 1
    repeated :drop_capabilities, :string, 2
  end
  add_enum "runtime.Protocol" do
    value :TCP, 0
    value :UDP, 1
  end
  add_enum "runtime.MountPropagation" do
    value :PROPAGATION_PRIVATE, 0
    value :PROPAGATION_HOST_TO_CONTAINER, 1
    value :PROPAGATION_BIDIRECTIONAL, 2
  end
end

module Runtime
  VersionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.VersionRequest").msgclass
  VersionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.VersionResponse").msgclass
  RunPodSandboxRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.RunPodSandboxRequest").msgclass
  RunPodSandboxResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.RunPodSandboxResponse").msgclass
  CreateContainerRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.CreateContainerRequest").msgclass
  CreateContainerResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.CreateContainerResponse").msgclass
  PodSandboxConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.PodSandboxConfig").msgclass
  PodSandboxMetadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.PodSandboxMetadata").msgclass
  DNSConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.DNSConfig").msgclass
  PortMapping = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.PortMapping").msgclass
  LinuxPodSandboxConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.LinuxPodSandboxConfig").msgclass
  LinuxSandboxSecurityContext = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.LinuxSandboxSecurityContext").msgclass
  NamespaceOption = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.NamespaceOption").msgclass
  SELinuxOption = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.SELinuxOption").msgclass
  ContainerConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.ContainerConfig").msgclass
  ContainerMetadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.ContainerMetadata").msgclass
  ImageSpec = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.ImageSpec").msgclass
  KeyValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.KeyValue").msgclass
  Mount = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.Mount").msgclass
  Device = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.Device").msgclass
  Int64Value = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.Int64Value").msgclass
  UInt64Value = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.UInt64Value").msgclass
  LinuxContainerConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.LinuxContainerConfig").msgclass
  LinuxContainerResources = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.LinuxContainerResources").msgclass
  LinuxContainerSecurityContext = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.LinuxContainerSecurityContext").msgclass
  Capability = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.Capability").msgclass
  Protocol = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.Protocol").enummodule
  MountPropagation = Google::Protobuf::DescriptorPool.generated_pool.lookup("runtime.MountPropagation").enummodule
end
